name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: https://hub.docker.com/
        username: preyashj
        password: Perfect@123

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        tags:  preyashj/backend:${{ github.sha }}
        push: true

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        tags:  preyashj/frontend:${{ github.sha }}
        push: true

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: v1.28.0

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.13.0

    - name: Deploy backend
      run: |
        helm upgrade --install backend ./helm-charts/backend \
          --namespace default \
          --set image.tag=${{ github.sha }}

    - name: Deploy frontend
      run: |
        helm upgrade --install frontend ./helm-charts/frontend \
          --namespace default \
          --set image.tag=${{ github.sha }}

